spring:
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .ftl
  thymeleaf:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        diarect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/Mysql?serverTimezone=Asia/Seoul
    username: root
    password: 1234
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
